steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/ui:latest'
      - '.'

  # Step 2: Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/ui:latest'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/ui:latest'
