version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "80:25565"
    volumes:
      - "mc-data:/data"
    environment:
      EULA: "TRUE"
      CONSOLE: "false"
      ENABLE_RCON: "falses"
#    restart: always

volumes:
  mc-data: