baseURL: https://blog.peterschen.de/
languageCode: en-us
title: Order to Management
paginate: 10
summaryLength: 12

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-134546123-1

minify:
  disableXML: true
  minifyOutput: true

mainSections: posts

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Order to Management
  description: Ramblings about all things Cloud. Views expressed are my own.
  cover: images/blog-header-5.png

  author: christoph
  DateFormat: "2 January 2006"

  assets:
    disableHLJS: true

taxonomies:
  author: authors

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: About
      url: /authors/christoph/
      weight: 20
    - identifier: imprint
      name: Imprint
      url: /imprint/
      weight: 30
    - identifier: privacy
      name: Privacy Policy
      url: /privacy-policy/
      weight: 40

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: monokai

  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS