baseURL: https://www.peterschen.de/
languageCode: en-us
title: Order to Management
paginate: 10
summaryLength: 40

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

services:
  googleAnalytics:
    ID: G-R7YMX3FVQ5

privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true

minify:
  disableXML: true
  minifyOutput: true

mainSections: posts

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Order to Management
  description: Ramblings about all things Cloud. Views expressed are my own.
  cover: images/blog-header-5.png

  contact:
    organization: peterschen.de
    street: Apostelweg 11
    city: Hamburg
    postal_code: 22143
    country: Germany

  author: christoph
  DateFormat: "2 January 2006"

  assets:
    disableHLJS: true

taxonomies:
  tag: tags
  author: authors

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: About
      url: /authors/christoph/
      weight: 20
    - identifier: imprint
      name: Imprint
      url: /imprint/
      weight: 30
    - identifier: privacy
      name: Privacy Policy
      url: /privacy-policy/
      weight: 40

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: monokai

  goldmark:
    renderer:
      unsafe: true

sitemap:
  changeFreq: monthly

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html
    - amp