main:
  params: [event]
  steps:
    - log_event:
      call: sys.log
      args:
        text: ${event}
        severity: INFO
    - check_operation:
      switch:
        condition: ${event.operation.last == true}
        return: ${event}